defprocess call_process_model do
  call_subprocess service_subprocess_model
  call_service do value = value + 1 end
  call_service do value = value + 1 end
  call_service do value = value + 1 end
end

defprocess service_subprocess_model do
  call_service do value = value + 1 end
  call_service do value = value + 1 end
  call_service do value = value + 1 end
end

defprocess choice_process_model do
  condition do
    value < 10
      call_service do value = "low" end
    value >= 10
      call_service do value = "high" end
  end
end
